replicaCount: 5

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.5.2
  pullPolicy: IfNotPresent

zookeeper:
  enabled: false

controller:
  replicaCount: 3
  persistence:
    enabled: true
    size: 8Gi
    storageClass: local-path

auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  sasl:
    enabled: true
    mechanism: PLAIN
    controllerMechanism: PLAIN
    interBrokerMechanism: PLAIN
    jaas:
      clientUsers:
        - admin
      clientPasswords:
        - admin-password
      interBrokerUser: admin
      interBrokerPassword: admin-password
      controllerUser: admin
      controllerPassword: admin-password

persistence:
  enabled: true
  size: 8Gi
  storageClass: local-path

externalAccess:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"