apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqls-operator
  namespace: homework
  labels:
    app: mysqls-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqls-operator
  template:
    metadata:
      labels:
        app: mysqls-operator
    spec:
      serviceAccountName: mysqls-crd-sa
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: operator-config-env
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"