apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: csi-s3
stringData:
  accessKeyID: "admin"
  secretAccessKey: "password123"
  endpoint: "http://minio.storage.svc.cluster.local:9000"