releases:
  - name: kafka-prod
    namespace: prod
    chart: ./charts/kafka
    values:
      - environments/prod-values.yaml
    wait: true
    timeout: 600
    
  - name: kafka-dev
    namespace: dev
    chart: ./charts/kafka
    values:
      - environments/dev-values.yaml
    wait: true
    timeout: 600