{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
{{- end }}