{{- if .Values.secrets.cdSaSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.cdSaSecret.name }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccounts.cd.name }}
type: kubernetes.io/service-account-token
{{- end }}