{{- if .Values.serviceAccounts.monitoring.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.monitoring.name }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.serviceAccounts.cd.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.cd.name }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
{{- end }}