global:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

server:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

repoServer:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

applicationSet:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

controller:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

redis:
  master:
    nodeSelector:
      node-role: infra
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
  replica:
    nodeSelector:
      node-role: infra
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule

dex:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

notifications:
  nodeSelector:
    node-role: infra
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule