apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: homework
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  namespaceSelector:
    matchNames:
      - homework
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics