apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Mi
  storageClassName: web-server-sc
