[all]
k8s-cp1 ansible_host=10.0.1.10 ansible_user=devops
k8s-cp2 ansible_host=10.0.1.11 ansible_user=devops
k8s-cp3 ansible_host=10.0.1.12 ansible_user=devops
k8s-w1  ansible_host=10.0.1.13 ansible_user=devops
k8s-w2  ansible_host=10.0.1.14 ansible_user=devops
k8s-w3  ansible_host=10.0.1.15 ansible_user=devops

[kube_control_plane]
k8s-cp1
k8s-cp2
k8s-cp3

[etcd]
k8s-cp1
k8s-cp2
k8s-cp3

[kube_node]
k8s-w1
k8s-w2
k8s-w3

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr
