apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: homework
spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - "https://example.com"
    volumeMounts:
      - name: workdir
        mountPath: "/init"
  containers:
  - name: web-server
    image: busybox:latest
    command:
    - httpd
    - "-f"
    - "-p"
    - "8000"
    - "-h"
    - "/homework"
    ports:
    - containerPort: 8000
    volumeMounts:
      - name: workdir
        mountPath: "/homework"
    lifecycle:
      preStop:
        exec:
          command: ['sh', '-c', 'rm -f /homework/index.html']   
  volumes:
  - name: workdir
    emptyDir: {}